# vi: set ft=ruby :
# Vikman Fernandez-Castro
# November 19, 2022

require_relative "../shared/shared.rb"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine316"
  config.vm.hostname = "alpine"
  config.vm.network "private_network", ip: $hosts[config.vm.hostname]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
    config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

    config.vm.provider "virtualbox" do |v|
      v.memory = $memory
      v.cpus = $cpus
      v.default_nic_type = "virtio"
    end

    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = $memory
      v.vmx["numvcpus"] = $cpus
    end
end
