# -*- mode: ruby -*-
# vi: set ft=ruby :

# Windows
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "agent_windows"        => {"box" => "tefanScherer/windows_2019"                                 , "autostart" => true},
  "windows-10"           => {"box" => "gusztavvargadr/windows-10"                                 , "autostart" => false},
  "windows-11"           => {"box" => "gusztavvargadr/windows-11"                                 , "autostart" => false},
  "windows-server-2012"  => {"box" => "addle/windows-server-2012-r2"                              , "autostart" => false},
  "windows-server-2008"  => {"box" => "galexshd/windows_2008_r2_virtualbox"                       , "autostart" => false},
  "windows-server-2003"  => {"box" => "therealslimpagey/Windows_Server_2003_Enterprise_R2_puppet" , "autostart" => false},
}
  
Vagrant.configure("2") do |config|
    machines.each do |name, vm|
        config.vm.define name, autostart: vm["autostart"] do |v|
            v.vm.box = vm["box"]
            v.vm.hostname = name
            v.vm.network "public_network", ip: $hosts[name], bridge: "wlp1s0"
        end
    end
    
    #config.vm.provision "file", source: "../shared", destination: "shared"
    #config.vm.provision "shell", path: "setup.sh", args: "--tumbleweed", env: {"SHARED_DIR" => "../shared"}, reboot: "yes"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = $memory
        v.cpus = $cpus
        v.default_nic_type = "virtio"
        
        v.customize ["modifyvm", :id, "--usb", "on"]
        v.customize ["modifyvm", :id, "--usbehci", "off"]
        v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']          
    end
end