# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 8, 2020

require_relative "../shared/shared.rb"

Vagrant.configure("2") do |config|

    config.vm.define "bullseye" do |bullseye|
      bullseye.vm.box = "debian/testing64"
      bullseye.vm.hostname = "bullseye"
      bullseye.vm.network "private_network", ip: $hosts[bullseye.vm.hostname]
    end

    config.vm.define "buster", autostart: false do |buster|
      buster.vm.box = "debian/buster64"
      buster.vm.hostname = "buster"
      buster.vm.network "private_network", ip: $hosts[buster.vm.hostname]
    end

    config.vm.provision "file", source: "../shared", destination: "shared"
    config.vm.provision "shell", path: "../shared/setup_deb.sh"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 4
      v.default_nic_type = "virtio"
    end
  end
