# -*- mode: ruby -*-
# vi: set ft=ruby :

# OpenSUSE
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "tumbleweed" => {"box" => "opensuse/Tumbleweed.x86_64", "autostart" => true},
  "leap"       => {"box" => "opensuse/Leap-15.4.x86_64" , "autostart" => false},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", args: "--tumbleweed", env: {"SHARED_DIR" => "/home/vagrant/shared"}, reboot: "yes"

  config.vm.provider "virtualbox" do |v|
    v.memory = $agentMemory
    v.cpus = $cpus
    v.default_nic_type = "virtio"
  end
end
