# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 25, 2022

require_relative "../shared/shared.rb"

machines = {
  "tumbleweed" => {"box" => "generic/opensuse15", "autostart" => false},
  "leap" => {"box" => "generic/opensuse15", "autostart" => true},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end
  end

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}, reboot: "yes"

  config.vm.provider "virtualbox" do |v|
    v.memory = $memory
    v.cpus = $cpus
    v.default_nic_type = "virtio"
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $memory
    v.vmx["numvcpus"] = $cpus
  end
end
