# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 25, 2022

require_relative "../shared/shared.rb"

Vagrant.configure("2") do |config|
  config.vm.define "tumbleweed" do |tumbleweed|
    tumbleweed.vm.box = "generic/opensuse15"
    tumbleweed.vm.hostname = "tumbleweed"
    tumbleweed.vm.network "private_network", ip: $hosts[tumbleweed.vm.hostname]
  end

  config.vm.define "leap", autostart: false do |leap|
    leap.vm.box = "generic/opensuse15"
    leap.vm.hostname = "leap"
    leap.vm.network "private_network", ip: $hosts[leap.vm.hostname]
  end

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", args: "--tumbleweed", env: {"SHARED_DIR" => "/home/vagrant/shared"}, reboot: "yes"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 8
    v.default_nic_type = "virtio"
  end
end
