# -*- mode: ruby -*-
# vi: set ft=ruby :

# Debian
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "amzn2"  => {"box" => "gbailey/amzn2"   , "autostart" => true },
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end

    config.vm.provider "virtualbox" do |v|
      if name == "ubuntu22"
        v.memory = $managerMemory
      else
        v.memory = $agentMemory
      end

      v.cpus = $cpus
      v.default_nic_type = "virtio"
      v.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    end

    config.vm.provider "vmware_desktop" do |v|
      if name == "ubuntu22"
        v.memory = $managerMemory
      else
        v.memory = $agentMemory
      end
      v.vmx["numvcpus"] = $cpus
    end    
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}
end
