# -*- mode: ruby -*-
# vi: set ft=ruby :

# Archlinux
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "archlinux" => {"box" => "generic/gentoo", "autostart" => true},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "public_network", ip: $hosts[name], bridge: "wlp1s0"
    end  
  end  

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "virtualbox" do |v|
    v.cpus = $cpus
    v.memory = $memory
    v.default_nic_type = "virtio"
  end
end
