# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# July 13, 2020

require_relative "../shared/shared.rb"

Vagrant.configure("2") do |config|
    config.vm.define "gentoo" do |gentoo|
      gentoo.vm.box = "generic/gentoo"
      gentoo.vm.hostname = "gentoo"
      gentoo.vm.network "public_network", ip: $hosts[gentoo.vm.hostname], bridge: "wlp1s0"
    end

    # The vboxsf filesystem is not installed so we can't share folders
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "file", source: "../shared", destination: "shared"
    config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

    config.vm.provider "virtualbox" do |v|
      v.cpus = $cpus
      v.memory = $memory
      v.default_nic_type = "virtio"
    end

    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = $memory
      v.vmx["numvcpus"] = $cpus
    end

  end
