# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 9, 2020

require_relative "../shared/shared.rb"

machines = {
  "impish" => {"box" => "generic/ubuntu2110", "autostart" => true},
  "hirsute" => {"box" => "generic/ubuntu2104", "autostart" => false},
  "groovy" => {"box" => "generic/ubuntu2010", "autostart" => false},
  "focal" => {"box" => "generic/ubuntu2004", "autostart" => false},
  "eoan" => {"box" => "generic/ubuntu1910", "autostart" => false},
  "bionic" => {"box" => "generic/ubuntu1804", "autostart" => false},
  "xenial32" => {"box" => "ubuntu/xenial32", "autostart" => false},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "../shared/setup_deb.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "virtualbox" do |v|
    v.cpus = $cpus
    v.memory = $memory
    # v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    v.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $memory
    v.vmx["numvcpus"] = $cpus
  end

end
