# -*- mode: ruby -*-
# vi: set ft=ruby :

# Debian
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "debian11"  => {"box" => "debian/bullseye64", "autostart" => true },
  "debian10"  => {"box" => "debian/buster64"  , "autostart" => false},
  "debian9"   => {"box" => "debian/stretch64" , "autostart" => false},
  "debian8"   => {"box" => "debian/jessie64"  , "autostart" => false},
  "ubuntu22"  => {"box" => "ubuntu/jammy64"   , "autostart" => true },
  "ubuntu20"  => {"box" => "generic/focal64"  , "autostart" => false},
  "ubuntu18"  => {"box" => "ubuntu/bionic64"  , "autostart" => false},
  "ubuntu16"  => {"box" => "ubuntu/xenial64"  , "autostart" => false},
  "ubuntu14"  => {"box" => "ubuntu/trusty64"  , "autostart" => false},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "virtualbox" do |v|
    v.memory = $memory
    v.cpus = $cpus
    v.default_nic_type = "virtio"
    v.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $memory
    v.vmx["numvcpus"] = $cpus
  end
end
