# -*- mode: ruby -*-
# vi: set ft=ruby :

# Debian
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "development" => {"box" => "generic/ubuntu2204" , "autostart" => true },
  "debian11"    => {"box" => "generic/debian11"   , "autostart" => false},
  "debian10"    => {"box" => "generic/debian10"   , "autostart" => false},
  "debian9"     => {"box" => "generic/debian9"    , "autostart" => false},
  "debian8"     => {"box" => "generic/debian8"    , "autostart" => false},
  "ubuntu22"    => {"box" => "generic/ubuntu2204" , "autostart" => false},
  "ubuntu21"    => {"box" => "generic/ubuntu2104" , "autostart" => false},
  "ubuntu20"    => {"box" => "generic/ubuntu2010" , "autostart" => false},
  "ubuntu18"    => {"box" => "generic/ubuntu1804" , "autostart" => false},
  "ubuntu16"    => {"box" => "generic/ubuntu1604" , "autostart" => false},
}

developmentVM = false

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end

    if (name == "development")
      developmentVM = true
    end

    config.vm.provider "virtualbox" do |v|
      if ( developmentVM || name == "ubuntu22" )
        v.memory = $managerMemory
      else
        v.memory = $agentMemory
      end

      v.cpus = $cpus
      v.default_nic_type = "virtio"
      v.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    end

    config.vm.provider "vmware_desktop" do |v|
      if ( developmentVM || name == "ubuntu22" )
        v.memory = $managerMemory
      else
        v.memory = $agentMemory
      end
      v.vmx["numvcpus"] = $cpus
    end    
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  
  # Provision development machine
  if developmentVM == true
    config.vm.synced_folder "~/Documents/wazuh/", "/vagrant", disabled: true
    config.vm.provision "shell", path: "setup.sh", args: "development", env: {"SHARED_DIR" => "/home/vagrant/shared"}
  else
    config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}
  end

end
