# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 9, 2020

require_relative "../shared/shared.rb"

Vagrant.configure("2") do |config|
  config.vm.define "centos8" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.hostname = "centos8"
    centos.vm.network "private_network", ip: $hosts[centos.vm.hostname]
  end

  config.vm.define "centos7", autostart: false do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos7"
    centos.vm.network "private_network", ip: $hosts[centos.vm.hostname]
  end

  config.vm.define "centos6", autostart: false do |centos|
    centos.vm.box = "centos/6"
    centos.vm.hostname = "centos6"
    centos.vm.network "private_network", ip: $hosts[centos.vm.hostname]
  end

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 4
    v.default_nic_type = "virtio"
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  end
