# -*- mode: ruby -*-
# vi: set ft=ruby :

# Gentoo
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
  "gentoo"  => {"box" => "generic/gentoo", "autostart" => true},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end  
  end

  # The vboxsf filesystem is not installed so we can't share folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "virtualbox" do |v|
    v.memory = $agentMemory
    v.cpus = $cpus
    v.default_nic_type = "virtio"
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $agentMemory
    v.vmx["numvcpus"] = $cpus
  end
end
