# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 9, 2020

require_relative "../shared/shared.rb"

machines = {
  "rocky" => {"box" => "generic/rocky9", "autostart" => true},
  "centos8" => {"box" => "bento/centos-stream-8", "autostart" => false},
  "centos7" => {"box" => "bento/centos-7", "autostart" => false},
  "centos6" => {"box" => "bento/centos-6", "autostart" => false},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]
    end
  end

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "virtualbox" do |v|
    v.memory = $memory
    v.cpus = $cpus
    v.default_nic_type = "virtio"
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $memory
    v.vmx["numvcpus"] = $cpus
  end

  end
