# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vikman Fernandez-Castro
# February 9, 2020

require_relative "../shared/shared.rb"

machines = {
  "rocky10" => {"box" => "bento/rockylinux-10", "autostart" => true},
  "rocky9" => {"box" => "bento/rockylinux-9", "autostart" => false},
  "alma10" => {"box" => "bento/almalinux-10", "autostart" => false},
  "alma9" => {"box" => "bento/almalinux-9", "autostart" => false},
  "fedora" => {"box" => "bento/fedora-latest", "autostart" => false},
  "centos10" => {"box" => "centos/stream10", "autostart" => false},
  "centos8" => {"box" => "bento/centos-stream-8", "autostart" => false},
  "centos7" => {"box" => "bento/centos-7", "autostart" => false},
  "centos6" => {"box" => "bento/centos-6", "autostart" => false},
}

Vagrant.configure("2") do |config|
  machines.each do |name, vm|
    config.vm.define name, autostart: vm["autostart"] do |v|
      v.vm.box = vm["box"]
      v.vm.hostname = name
      v.vm.network "private_network", ip: $hosts[name]

      v.vm.provider "virtualbox" do |vb|
        vb.memory = $memory
        vb.cpus = $cpus
        vb.customize ["modifyvm", :id, "--audio", "none"]

        # Only use virtio if not centos6
        vb.default_nic_type = "virtio" unless name == "centos6"
      end
    end
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../shared", destination: "shared"
  config.vm.provision "shell", path: "setup.sh", env: {"SHARED_DIR" => "/home/vagrant/shared"}

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = $memory
    v.vmx["numvcpus"] = $cpus
  end

  end
